### ISSUE TITLE
好像不支持如何支持docker容器，从win10到centos7？

### ISSUE THREAD

**Issue by lyreee** [sumneko/vscode-lua#13]
你好，看market上提示不支持linux和macos，需要编译。我在win10下工作。
经验证，实际使用中WSL是ok的，但容器里的centos7的确不行。
OUTPUT的提示如下
/root/.vscode-server/extensions/sumneko.lua-0.15.5/server/bin/Linux/lua-language-server: ...server/extensions/sumneko.lua-0.15.5/server/platform.lua:16: It doesn't seem to support your OS, please build it in your OS,...

是否能具体说明下，或者我可以做些什么来改进？

**Comment by sumneko** [comment]
参考 https://github.com/sumneko/vscode-lua/wiki/Build
