### ISSUE TITLE
 It doesn't seem to support your OS, please build it in your OS...

### ISSUE THREAD

**Issue by MorseWayne** [sumneko/vscode-lua#19]
Connection to server got closed. Server will restart.
/root/.vscode-server/extensions/sumneko.lua-0.16.1/server/bin/Linux/lua-language-server: ...server/extensions/sumneko.lua-0.16.1/server/platform.lua:16: It doesn't seem to support your OS, please build it in your OS, see https://github.com/sumneko/vscode-lua/wiki/Build
exePath: /root/.vscode-server/extensions/sumneko.lua-0.16.1/server/bin/Linux/lua-language-server
exeDir:  /root/.vscode-server/extensions/sumneko.lua-0.16.1/server/bin/Linux
dll:     so
cpath:   /root/.vscode-server/extensions/sumneko.lua-0.16.1/server/bin/Linux/?.so

stack traceback:
	[C]: in function 'error'
	...server/extensions/sumneko.lua-0.16.1/server/platform.lua:16: in main chunk
	...ode-server/extensions/sumneko.lua-0.16.1/server/main.lua:3: in main chunk
	[C]: in ?

更新到最新的0.16.1版本之后就出现这个问题了, 我知道是我的Ubuntu版本太老的问题，但是我想知道怎么编译自己的版本啊：
   Open repo and execute tasks in VSCode
1. PreCompile
2. Compile
3. Install
这个Readme给的这个步骤着实有点懵（萌新），不知道该怎么执行，目前我使用的Ubuntu版本是16.04 LTS Server，望大佬指点一下。

**Comment by sumneko** [comment]
按 F1 ，输入 run task

**Comment by MorseWayne** [comment]
> 按 F1 ，输入 run task
谢谢了，不过我昨晚已经重新编译了bee.so放在插件目录的lib里解决了这个问题。
