### ISSUE TITLE
如何在macOS上编译安装

### ISSUE THREAD

**Issue by 18672008811** [sumneko/vscode-lua#21]
看到在macos上需要手动安装
其中最后的步骤
* Open repo and execute tasks in VSCode
    1. PreCompile
    2. Compile
    3. Install
具体要怎样操作？
拜求指点，谢谢！

**Comment by sumneko** [comment]
按 F1 ，输入 run task

**Comment by 18672008811** [comment]
谢谢回复，已经在mac上成功安装并能正常使用
但是，昨天用了，今天重新开机后，又报错无法使用，请问是什么原因，如何处理呢？
报错信息：
[Info  - 11:36:06 AM] Connection to server got closed. Server will restart.
/Users/tyj/.vscode/extensions/sumneko.lua-0.16.3/server/bin/macOS/lua-language-server: error loading module 'lpeglabel' from file '/Users/tyj/.vscode/extensions/sumneko.lua-0.16.3/server/bin/macOS/lpeglabel.so':
	dlopen(/Users/tyj/.vscode/extensions/sumneko.lua-0.16.3/server/bin/macOS/lpeglabel.so, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/tyj/.vscode/extensions/sumneko.lua-0.16.3/server/bin/macOS/lpeglabel.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/tyj/.vscode/extensions/sumneko.lua-0.16.3/server/bin/macOS/lpeglabel.so
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	...xtensions/sumneko.lua-0.16.3/server/script/workspace.lua:4: in main chunk
	[C]: in function 'require'
	...s/sumneko.lua-0.16.3/server/script/method/initialize.lua:1: in main chunk
	[C]: in function 'require'
	...ensions/sumneko.lua-0.16.3/server/script/method/init.lua:4: in local 'init'
	...ensions/sumneko.lua-0.16.3/server/script/method/init.lua:8: in main chunk
	[C]: in function 'require'
	.../extensions/sumneko.lua-0.16.3/server/script/service.lua:2: in main chunk
	[C]: in function 'require'
	...yj/.vscode/extensions/sumneko.lua-0.16.3/server/main.lua:20: in main chunk
	[C]: in ?

**Comment by 18672008811** [comment]
目前发现 扩展应用商店回退版本到 0.16.2
使用旧的vscode-lua 重新编译安装
可以成功使用
