### ISSUE TITLE
Is it possible to upload vsix files to GitHub release?

### ISSUE THREAD

**Issue by yaegassy** [sumneko/vscode-lua#25]
Thanks for this language server!

Can I ask you to upload a vsix file to GitHub release when I version up?

**e.g.** vscode-eslint: https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.4-next.1

I mainly use Vim and use lua-language-server built, but would like to use the pre-built version if possible.

The vsix files for VSCode that come with `bin/lua-language-server` and `server` directories are very useful.

**Comment by sumneko** [comment]
I'll try to do this, thanks for your suggest!

**Comment by yaegassy** [comment]
If you can, please upload the current and latest version of vsix to the GitHub release first.

**Comment by yaegassy** [comment]
I use the LSP client plugins vim-lsp and coc.nvim in vim.

Thanks to uploading to the GitHub release, installation and use of Language Server is now easier.

![sumneko-lua-language-server_960](https://user-images.githubusercontent.com/188642/88454217-e8930c00-cea8-11ea-9a81-c23029171a82.gif)
