### ISSUE TITLE
build vsix and show error when launch

### ISSUE THREAD

**Issue by EricDDK** [sumneko/vscode-lua#26]
![image](https://user-images.githubusercontent.com/33505774/93978721-f7b20f80-fdae-11ea-859b-fa0a26cc0691.png)
I want to secondary development. 
I finished everything in tutorial https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone) .
Then I vsce package, but the extension show error.

**Comment by sumneko** [comment]
`cd client` then `npm install`

**Comment by EricDDK** [comment]
> npm install

finshed it, but the extension still has no function. not output log.

**Comment by sumneko** [comment]
Did you compile the TypeScript of client? Press `Ctrl + Shift + B` and select `client/tsconfig.json`.

**Comment by EricDDK** [comment]
> Did you compile the TypeScript of client? Press `Ctrl + Shift + B` and select `client/tsconfig.json`.

error TS5023: Unknown option 'p'
Use the '--help' flag to see options.
error TS5007: Cannot resolve referenced file: 'd:\work\Plugin\vscode-lua\client\tsconfig.json'.
The terminal process "C:\Windows\System32\cmd.exe /d /c tsc -p d:\work\Plugin\vscode-lua\client\tsconfig.json" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by sumneko** [comment]
try update your TypeScript by `npm install -g typescript`

**Comment by EricDDK** [comment]
> try update your TypeScript by `npm install -g typescript`

I remove path by https://stackoverflow.com/questions/32497809/windows-10-tsc-error-ts5007-cannot-resolve-referenced-file-tsconfig-json.
comile is over. but extension still has no functions.

**Comment by EricDDK** [comment]
> try update your TypeScript by `npm install -g typescript`

Can you send me a whole project ? I don't know where is wrong.

**Comment by EricDDK** [comment]
> try update your TypeScript by `npm install -g typescript`

![image](https://user-images.githubusercontent.com/33505774/93982662-136be480-fdb4-11ea-88b1-bc51bdc50ddb.png)

**Comment by sumneko** [comment]
You could download `vsix` from `https://github.com/sumneko/vscode-lua`, then unzip it.

**Comment by EricDDK** [comment]
> You could download `vsix` from https://github.com/sumneko/vscode-lua/releases, then unzip it.

I cmd "bin\Windows\lua-language-server.exe -E main.lua" 
then show
![image](https://user-images.githubusercontent.com/33505774/93983592-5a0e0e80-fdb5-11ea-8806-0a5c271aa080.png)

**Comment by EricDDK** [comment]
> You could download `vsix` from https://github.com/sumneko/vscode-lua/releases, then unzip it.

I download and compare them. I found that there are many folders in my package that are not in your package, most of which are compiled files. but others are same.

by the logs when cmd "bin\Windows\lua-language-server.exe -E main.lua", is server has something wrong?

**Comment by sumneko** [comment]
There is a bug, see https://github.com/sumneko/lua-language-server/commit/57bfae9cd5a176c68f5874f8dad47db4f9e29174 .
Thank you.

**Comment by EricDDK** [comment]
> There is a bug, see [sumneko/lua-language-server@57bfae9](https://github.com/sumneko/lua-language-server/commit/57bfae9cd5a176c68f5874f8dad47db4f9e29174) .
> Thank you.

```
[exthost] [error] Error: Cannot find module 'semver'
```

**Comment by sumneko** [comment]
I guess you use `npm install` in the root path.
You should use it in `client` path, because only the client is implemented in TypeScript.

**Comment by EricDDK** [comment]
> I guess you use `npm install` in the root path.
> You should use it in `client` path, because only the client is implemented in TypeScript.

No. it;s a path system environment problem.
I give up to build it.

Thanks.
