### ISSUE TITLE
Lua does not support this grammar (with some assignment operators in LuaU)

### ISSUE THREAD

**Issue by K4K4SH11** [sumneko/vscode-lua#32]
LuaU is a gradually typed embeddable scripting language derived from Lua which you can read on [here](https://roblox.github.io/luau/).
I know it isn't regular lua 5.4+ but it adds some extra assignment operators that lua is yet to add, which can be found in most other programming languages such as +=, -=, *=, /= etc

I couldn't find a "quick fix" for it appearing as a grammatical error, I tried to disable linting on them but it didn't work either, could you add support for these operators or an option to ignore highlighting?

**Comment by K4K4SH11** [comment]
Oh I just saw the "Nonstandard Symbol" options in settings, nevermind.
Though prechecking parameters being highlighted like `function name(a : nil, b : string)` is something I still can't find a fix for.

**Comment by sumneko** [comment]
see https://github.com/sumneko/lua-language-server/wiki/Plugin-(Experimental)

**Comment by K4K4SH11** [comment]
Where do I put that in the plugin folder, does it need to be a function of the module being returned?
Also how do I stop this from happening I accidentally enabled semantic tokens 
![image](https://user-images.githubusercontent.com/39433002/106633073-574ad380-6576-11eb-800d-952fc1fb73c5.png)
