### ISSUE TITLE
Class Inheritance - Auto complete

### ISSUE THREAD

**Issue by rollnthndr** [sumneko/vscode-lua#33]
Hi,

Here is an example of large lua project that heavily uses 'classes' and inheritance. Any chance to get auto-completion working with something like this?

I'm have no idea of the magnitude a solution this would require, just asking.

Thanks!

https://github.com/FlightControl-Master/MOOSE/tree/develop/Moose%20Development/Moose

**Comment by sumneko** [comment]
Use EmmyLua, there are some examples : https://github.com/sumneko/lua-language-server/discussions/389
