### ISSUE TITLE
Auto complete on empty line

### ISSUE THREAD

**Issue by YpsilonTM** [sumneko/vscode-lua#34]
![4DuxsCPPhd](https://user-images.githubusercontent.com/22861150/108635617-8e7b1900-7480-11eb-8404-886f8e25c58f.gif)
On empty lines suddenly the the autocomplete menu already opens.
So if I spam "Enter" a few times it keeps adding the first thing in the list.
I can only imagine that lua is causing this because the suggested syntax list hasn't been updated in more than a year.

Could be that your extention is not causing this. Maybe its even a VSC issue But I am just letting you know the issue.

Big Love <3 Ypsilon

**Comment by sumneko** [comment]
Duplicate with https://github.com/sumneko/lua-language-server/issues/401
