### ISSUE TITLE
[request] optional parameter annotation support

### ISSUE THREAD

**Issue by Magnymbus** [sumneko/vscode-lua#35]
Specifically, as implemented in LDoc:

`@param**[opt]**` which denotes optional parameters and displays them as ` function FunctionName([, optional param])` in hints/tips

`@param[opt=**param default**]` which denotes the default value of the optional parameter and displays them as `function FunctionName([, optional param=param default])`  in hints/tips

`@param[optchain]` to denote a chain of optional parameters that depend on previous parameters and displays them as `function FunctionName(param [, optional param [, optchain layer 1 [, optchain layer 2, etc.]]])`

.

Other, unrelated features from LDoc would be very appreciated. Such as:

`@return[#]` as return groups, denoting variables that are returned together when there are conditional returns and displays them as 
```
->return group 1 with only one variable: type
2.
    1. return group 2 variable 1: type
    2. return group 2 variable 2: type
3. return group 3 with only one variable: type
```

`@see` to reference another documented item and displays them as a link to their documentation on hints/tips

.

Most other features of LDoc are only useful for generating HTML documentation, so should probably be explicitly ignored unless you want to bother figuring out how to display them.

**Comment by sumneko** [comment]
This extension already provides EmmyLua as a solution for type annotation and documentation, so other similar functions will not be supported for the time being.
