### ISSUE TITLE
Build and Run (In VSCode) not working on pre-compile

### ISSUE THREAD

**Issue by solar-core** [sumneko/vscode-lua#38]
Hello! I use this instructions https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(In-VSCode)
When i open the repository directory by VSCode and run task PreCompile it shows me this error
`> Executing task: chcp 65001 && msvc_x64.bat <

Active code page: 65001
'msvc_x64.bat' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\Windows\System32\cmd.exe /c chcp 65001 && msvc_x64.bat" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.`
I am using Windows 10 and VSCode 1.55.0
I have Visual Studio 2019 with C++ installed

**Comment by grapereader** [comment]
Also having this issue; I think the build commands are out of date.

There have been 2 changes to the location of this file:
First from `msvc_x64.bat` to `compile/msvc_x64.bat` https://github.com/actboy168/luamake/commit/8e79e012c9dc1ea712d60e98a6b4cd2b1f956fc0
Then from `compile/msvc_x64.bat` to `compile/install.bat` https://github.com/actboy168/luamake/commit/e566333862d10042b1a24dd00942cf47214445dc

After changing the Windows command to `"chcp 65001 && compile\\install.bat"` in tasks.json I can get past the PreCompile step.

Unfortunately from there more things are broken. I will keep trying to work through it.
