### ISSUE TITLE
Parameter hint is unreliable even at high search depth

### ISSUE THREAD

**Issue by SonoSooS** [sumneko/vscode-lua#41]
I tried toying around with the settings, but can't get all :gsub calls to display the parameter name.

It seems like it's not fully the fault of the parameter hint processor, because where the parameter name hint is not displayed, the function signature is also invalid.

![image](https://user-images.githubusercontent.com/7823099/124523069-b21e7a80-ddf5-11eb-8da9-52630c285c75.png)
![image](https://user-images.githubusercontent.com/7823099/124523085-c4001d80-ddf5-11eb-932b-f7ef09e094a8.png)
![image](https://user-images.githubusercontent.com/7823099/124523089-c9f5fe80-ddf5-11eb-98fe-0b12f8eae3ee.png)

This seems to be very intermitten. Most of the times only the first 3 display (like on the screenshot), but sometimes even 5 displays if I keep changing the search depth, search time, and other relevant config values.

**Comment by sumneko** [comment]
Should be fixed.
