### ISSUE TITLE
Installing extension breaks extension loading on 1.60-insider

### ISSUE THREAD

**Issue by disco0** [sumneko/vscode-lua#42]
<details>
<summary>Version Info</summary>
```
Version: 1.60.0-insider
Commit: 1ee61f368ee0570feeb220605578a8768d99e762
Date: 2021-08-09T05:59:19.046Z (19 hrs ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0
```
</details>

Installing latest version from marketplace and restarting Insiders causes extension loading to fail, and installed extensions cannot be interacted with—uninstalling and restarting reverses the behaviour.

It seems there's a few extensions doing this: [microsoft/vscode#130219](https://github.com/microsoft/vscode/issues/130219#issuecomment-895652916)

**Comment by sumneko** [comment]
I think this is an issue of VSCode 1.60-insider

**Comment by sumneko** [comment]
Seems fixed in latest VSCode insider
