### ISSUE TITLE
support $/requestHint

### ISSUE THREAD

**Issue by xiyaowong** [sumneko/vscode-lua#45]
目前inlay-hint貌似不太准确，总是缺了东西 #41 ，想问下啥时候发布支持server最新的`$/requestHint`。我也看了你的提交，貌似没有正常跑起来，不知道现在你解决了没

**Comment by sumneko** [comment]
#41 这个应该早就解决了，只是这边的issue我一直没管。
这个项目是把语言服务器包装成VSCode的插件并发布到VSCode市场中，如果有语言服务器本身的问题请在服务器项目问。

**Comment by xiyaowong** [comment]
了解了:smile:

**Comment by xiyaowong** [comment]
我知道我的问题了。设置在`Lua.workspace.library`中的函数没有内联信息
