### ISSUE TITLE
feat(build): Support linux-arm64

### ISSUE THREAD

**Issue by 4513ECHO** [sumneko/vscode-lua#54]
I want to use the project with linux-arm64 platform but no binary release exists now. How about add support?

**Comment by sumneko** [comment]
see https://github.com/sumneko/lua-language-server/issues/891

**Comment by 4513ECHO** [comment]
I see. I keep this issue open until we resolve that issue.

**Comment by aidos** [comment]
Looks like you've got it figured out now @sumneko. Looking forward to having this working on ARM. Thanks for your hard work!

**Comment by 4513ECHO** [comment]
Since the release of [`2.6.8`](https://github.com/sumneko/lua-language-server/releases/tag/2.6.8), lua-language-server has pre-compiled binary release for linux-arm64. Thank you very much!
