### ISSUE TITLE
Ubuntu nvim format 会在行尾出现^M

### ISSUE THREAD

**Issue by fastchaser** [sumneko/vscode-lua#55]
感谢大佬的工作
我在Ubuntu1804上nvim0.61使用nvim-lsp-installer更新最新版sumneko_lua后，可以格式化lua代码了，耶✌️
但是在每行末尾都会出现^M（windows的换行符），哈哈🙈

**Comment by sumneko** [comment]
是 WSL 吗？

**Comment by fastchaser** [comment]
不是，ubuntu1804系统，默认终端 nvim

**Comment by sumneko** [comment]
看看2.6.6修复没

**Comment by sumneko** [comment]
应该有个类似于 `cmd = {'lua-language-server'}` 的地方，改成 `cmd = {'lua-language-server', '--preview'}`

**Comment by fastchaser** [comment]
可以了，感谢大佬👍 👍 👍
