### ISSUE TITLE
`const` keyword not recognized using Lua  5.4 runtime

### ISSUE THREAD

**Issue by thadeudepaula** [sumneko/vscode-lua#59]
Using version 3.2.2 of lua-language-server, it hints const as a variable, not as a keyword.

```Lua
require("lsp-config").setup("sumneko_lua", {
    settings = {
      rootPatterns = {".git/"},
      Lua = {
        runtime = {
          version = 'Lua 5.4',
          path = {
            '?.lua',
            '?/init.lua',
            vim.fn.expand'~/.luarocks/share/lua/5.4/?.lua',
            vim.fn.expand'~/.luarocks/share/lua/5.4/?/init.lua',
            '/usr/share/5.4/?.lua',
            '/usr/share/lua/5.4/?/init.lua'
          }
        },
        diagnostics = {
            enable  = true,
            globals = {"vim"},
            disable = {"lowercase-global"}
        },
        workspace = {
          library = {
            vim.fn.expand'~/.luarocks/share/lua/5.4',
            '/usr/share/lua/5.4'
          }
        },
        telemetry = {
          enable = false
        }
      }
    }
  })
```

<img width="290" alt="nvim-lualsp" src="https://user-images.githubusercontent.com/78352532/167337295-7e30fa5b-96ef-42f9-9fba-0f525173cdef.png">

**Comment by sumneko** [comment]
Should be `local x <const> = 10`

**Comment by thadeudepaula** [comment]
Sorry... just opened editor and started setting it to work with Lua 5.4; as the code ran without complain, I don't minded the error syntax

```
function lala()
   local x <const> = 10
   print(x)
end

function lele()
  local const x = 10
  print(x)
end

lala()
lele()
```

**Comment by sumneko** [comment]
> Sorry... just opened editor and started setting it to work with Lua 5.4; as the code ran without complain, I don't minded the error syntax
> 
> ```lua
> function lala()
>    local x <const> = 10
>    print(x)
> end
> 
> function lele()
>   local const x = 10
>   print(x)
> end
> 
> lala()
> lele()
> ```

What, I have tested this and found it is correct syntax.
I just not know before, I will check the document of Lua 5.4.
