### ISSUE TITLE
Add a config to set custom language server path

### ISSUE THREAD

**Issue by necauqua** [sumneko/vscode-lua#65]
On NixOS the binary bundled with this plugin does not work because NixOS has unusual linker location.

I have to install `sumneko-lua-language-server` package from the package manager and link it into the extension folder replacing bundled binary as a workaround.

However I have to update the link on every plugin update, which is tedious - it would be better if I was able to use the system language server (by setting the path to it in the config).

**Comment by sumneko** [comment]
I only provide the language client in VSCode.
Are you using VSCode?

**Comment by necauqua** [comment]
Yes

The `.vscode/extensions/sumneko.lua-3.5.3-linux-x64/server/bin/lua-language-server` binary does not work on NixOS - that's just how it is, no binary usually works on NixOS without patching the linker path specifically for it.

So I install the `lua-language-server` from [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/tools/sumneko-lua-language-server/default.nix) which has that linker patch - and `ln -s` that into the `.vscode/extensions/sumneko.lua-3.5.3-linux-x64/server/bin/` folder.

But on every update I have to `ln -s` it again, and it would be great if there was a setting in VSCode to set custom path for the server binary.

**Comment by necauqua** [comment]
I wanted to mention that I noticed that rust-analyzer actualy [does patch](https://github.com/rust-lang/rust-analyzer/blob/4904b2bdf8797f14fff3b585d18207161126acce/editors/code/src/main.ts#L294) their LSP binary specifically for NixOS, heh

That's too much to ask for though, I'll be happy with just the config parameter (which should be easy to implement) I asked for

**Comment by sumneko** [comment]
Has supported since 3.6.0
