### ISSUE TITLE
Newline converts previous line's indentation into spaces regardless of settings, introduced in v3.5.4

### ISSUE THREAD

**Issue by WasabiRaptor** [sumneko/vscode-lua#68]
On hitting enter at the end of a line to create a newline, the tabs on the previous line are converted into spaces, while the newline does have the correct tab indentation as per my VSC settings

I saw that in the changelog of v3.5.4 there was "NEW type-formatting: fix wrong indentation of VSCode" and then went to the prior version, and did not have this issue, and then tested that version, and the issue was there

**Comment by sumneko** [comment]
Should be fixed.
