### ISSUE TITLE
Errors often get stuck even after fixing them

### ISSUE THREAD

**Issue by melyux** [sumneko/vscode-lua#71]
Here's an example:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/10296053/207028067-05b38fbb-0faf-4e45-a5c3-2f9032269ba2.png">

It stuck around even after I used the variable and even changed its name.

Seems like the whole error-checking just freezes. It won't find new errors either.

**Comment by sumneko** [comment]
This extension dose not contain `luacheck`, I think you are using other extension.

**Comment by melyux** [comment]
My bad, the names are identical. You're right
